export const environment = {
  production: true,
  page_size: 10,
  page_size_options: [10, 20, 50, 100],
  ckeditor_toolbar: [
    'Heading',
    'uploadImage',
    'PageBreak',
    'FontBackgroundColor',
    'Alignment',
    'FontColor',
    'FontFamily',
    'FontSize',
    //'TextTransformation',
    'bold',
    'italic',
    'underline',
    'link',
    'bulletedList',
    'numberedList',
    '|',
    '|',
    //'imageUpload',
    'blockQuote',
    'insertTable',
    'undo',
    'redo',
    'MathType',
    'ChemType',
    'MediaEmbed',
    //'CKFinder',
    //'CKFinderUploadAdapter',
    'HorizontalLine',
    //'Essentials',
    'Highlight',
    //'Image',
    //'ImageCaption',
    'ImageResize',
    //'ImageStyle',
    //'ImageToolbar',
    //'List',
    //'Paragraph',
    'SpecialCharacters',
    //'Table',
    //'TableToolbar',
    //'htmlSource',
  ],
  // apiUrl: 'https://apidev.proceum.com/api/',
  apiUrl: 'https://apiuat.proceum.com/api/',
  //apiUrl: 'https://apiuat.proceum.com/api/',
};
